"""
Pre-extracted policy data from real medical drug coverage documents.
Used for demo/development without requiring Supabase or Gemini API keys.
"""

SEED_POLICIES = [
    {
        "drug_name": "Bevacizumab (Avastin)",
        "payer_name": "Blue Cross NC",
        "hcpcs_code": "J9035",
        "covered_indications": [
            "Metastatic colorectal cancer",
            "Non-squamous non-small cell lung cancer (first-line)",
            "Recurrent glioblastoma in adults",
            "Metastatic renal cell carcinoma",
            "Persistent, recurrent, or metastatic cervical cancer",
            "Epithelial ovarian, fallopian tube, or primary peritoneal cancer",
            "Unresectable or metastatic hepatocellular carcinoma",
        ],
        "prior_auth_checklist": [
            {
                "requirement": "FDA-labeled indication with appropriate genetic/diagnostic testing",
                "patient_friendly": "Your diagnosis must match an officially approved use for this drug, and required lab tests must confirm eligibility",
                "action_needed": "Ask your doctor to run any required genetic or diagnostic tests and include results in the prior auth request",
            },
            {
                "requirement": "Trial and documented serious adverse event to both preferred bevacizumab biosimilars (Mvasi and Zirabev)",
                "patient_friendly": "You must first try the preferred, lower-cost versions of this drug (Mvasi and Zirabev) and have a documented serious side effect from both",
                "action_needed": "Your doctor must document the serious adverse event and submit an FDA MedWatch form for each preferred biosimilar tried",
            },
            {
                "requirement": "No disease progression or unacceptable toxicity on same treatment class",
                "patient_friendly": "Your cancer must not have gotten worse while on a similar treatment before",
                "action_needed": "Your oncologist needs to document your treatment history showing you haven't progressed on this type of drug",
            },
            {
                "requirement": "Dosing within FDA-labeled or NCCN 1/2A compendia supported range",
                "patient_friendly": "The amount of drug prescribed must follow standard medical guidelines",
                "action_needed": "Your doctor will ensure the prescription follows approved dosing schedules",
            },
            {
                "requirement": "No FDA-labeled contraindications",
                "patient_friendly": "You must not have any medical conditions that make this drug unsafe for you",
                "action_needed": "Review your medical history with your doctor to confirm there are no safety concerns",
            },
        ],
        "step_therapy_roadmap": [
            {
                "step_number": 1,
                "drug_name": "Mvasi (bevacizumab-awwb)",
                "patient_explanation": "Your plan requires you to start with Mvasi first. It's a biosimilar that works the same way as Avastin but costs less. Most patients do well on it.",
                "duration": "Continue unless serious adverse event occurs",
                "tip": "Mvasi is FDA-approved and clinically equivalent to Avastin. Ask your doctor about any concerns.",
            },
            {
                "step_number": 2,
                "drug_name": "Zirabev (bevacizumab-bvzr)",
                "patient_explanation": "If Mvasi caused a serious side effect, your plan will then cover Zirabev as the next option. Your doctor must document what happened with Mvasi.",
                "duration": "Continue unless serious adverse event occurs",
                "tip": "Make sure your doctor files an FDA MedWatch report for the Mvasi adverse event — it's required for approval.",
            },
            {
                "step_number": 3,
                "drug_name": "Avastin (bevacizumab)",
                "patient_explanation": "If both Mvasi and Zirabev caused documented serious adverse events, your plan will cover brand-name Avastin. FDA MedWatch reports are required for both prior drugs.",
                "duration": "365-day approval, then renewal",
                "tip": "Keep copies of all adverse event documentation. Your doctor will need to resubmit for annual renewal.",
            },
        ],
        "patient_summary": "Blue Cross NC covers Avastin (bevacizumab) for several types of cancer, but requires you to first try two lower-cost biosimilar versions (Mvasi and Zirabev). You can only get brand-name Avastin if both biosimilars caused documented serious side effects. Approval lasts one year and requires renewal.",
    },
    {
        "drug_name": "Trastuzumab (Herceptin)",
        "payer_name": "Blue Cross NC",
        "hcpcs_code": "J9355",
        "covered_indications": [
            "HER2-overexpressing breast cancer (adjuvant and metastatic)",
            "HER2-overexpressing metastatic gastric or gastroesophageal junction adenocarcinoma",
        ],
        "prior_auth_checklist": [
            {
                "requirement": "HER2 protein overexpression confirmed by FDA-approved companion diagnostic",
                "patient_friendly": "Your tumor must test positive for HER2 using a specific FDA-approved test",
                "action_needed": "Ask your oncologist to order HER2 testing (IHC or FISH) from a certified lab and include results with the authorization request",
            },
            {
                "requirement": "Trial and documented serious adverse event to ALL preferred trastuzumab biosimilars (Ogivri, Ontruzant, Trazimera)",
                "patient_friendly": "You must first try all three preferred biosimilar versions and have documented serious side effects from each one",
                "action_needed": "Your doctor must file FDA MedWatch reports for each biosimilar that caused a serious adverse event",
            },
            {
                "requirement": "No substitution with ado-trastuzumab emtansine or fam-trastuzumab deruxtecan",
                "patient_friendly": "Herceptin cannot be swapped for Kadcyla or Enhertu — these are different drugs despite similar names",
                "action_needed": "Ensure your prescription specifically states trastuzumab (Herceptin), not a conjugated version",
            },
        ],
        "step_therapy_roadmap": [
            {
                "step_number": 1,
                "drug_name": "Ogivri (trastuzumab-dkst)",
                "patient_explanation": "Your plan requires starting with Ogivri, a biosimilar that works identically to Herceptin for HER2-positive cancers.",
                "duration": "Continue unless serious adverse event occurs",
                "tip": "Ogivri has been proven clinically equivalent to Herceptin in large studies.",
            },
            {
                "step_number": 2,
                "drug_name": "Ontruzant (trastuzumab-dttb)",
                "patient_explanation": "If Ogivri caused a serious side effect, your plan will cover Ontruzant next. Documentation of the Ogivri reaction is required.",
                "duration": "Continue unless serious adverse event occurs",
                "tip": "Your doctor must submit an FDA MedWatch report for the Ogivri adverse event.",
            },
            {
                "step_number": 3,
                "drug_name": "Trazimera (trastuzumab-qyyp)",
                "patient_explanation": "If both Ogivri and Ontruzant caused serious side effects, Trazimera is the next option before brand-name Herceptin.",
                "duration": "Continue unless serious adverse event occurs",
                "tip": "FDA MedWatch reports are required for both previous biosimilar adverse events.",
            },
            {
                "step_number": 4,
                "drug_name": "Herceptin (trastuzumab)",
                "patient_explanation": "Brand-name Herceptin is covered only after documented serious adverse events from all three preferred biosimilars (Ogivri, Ontruzant, and Trazimera).",
                "duration": "365-day approval, then renewal",
                "tip": "This is the longest step therapy pathway — maintain thorough records of all adverse events and MedWatch submissions.",
            },
        ],
        "patient_summary": "Blue Cross NC covers Herceptin for HER2-positive breast cancer and gastric cancer, but requires trying three biosimilar alternatives first (Ogivri, Ontruzant, then Trazimera). Brand-name Herceptin is only approved after documented serious adverse events from all three. HER2 testing is required before starting treatment.",
    },
    {
        "drug_name": "Rituximab (Rituxan)",
        "payer_name": "Cigna",
        "hcpcs_code": "J9312",
        "covered_indications": [
            "Rheumatoid arthritis (with methotrexate, after TNF inhibitor failure)",
            "ANCA-associated vasculitis (granulomatosis with polyangiitis, microscopic polyangiitis)",
            "Pemphigus vulgaris",
            "Multiple sclerosis",
            "Myasthenia gravis (anti-MuSK antibody-positive)",
            "Neuromyelitis optica spectrum disorder",
            "Systemic lupus erythematosus",
            "Immune thrombocytopenia (ITP)",
            "Membranous nephropathy",
            "Pediatric nephrotic syndrome",
            "Graft-versus-host disease (chronic)",
            "Autoimmune hemolytic anemia",
            "Thrombotic thrombocytopenic purpura",
        ],
        "prior_auth_checklist": [
            {
                "requirement": "Prior authorization required; prescribed by or in consultation with specialist in condition being treated",
                "patient_friendly": "Your doctor must get pre-approval, and the prescription must come from a specialist who treats your condition",
                "action_needed": "Make sure your treating specialist submits the prior authorization request — a general practitioner cannot prescribe this without specialist involvement",
            },
            {
                "requirement": "For RA: trial of one conventional DMARD for at least 3 months",
                "patient_friendly": "For rheumatoid arthritis, you must have tried a standard RA medication (like methotrexate) for at least 3 months first",
                "action_needed": "Ask your rheumatologist to document your DMARD treatment history, including start date and duration",
            },
            {
                "requirement": "For MS: inadequate response to at least TWO disease-modifying therapies",
                "patient_friendly": "For multiple sclerosis, you must have tried at least two other MS medications that didn't work well enough",
                "action_needed": "Your neurologist needs to document the names of the two MS drugs tried, how long you were on them, and why they were inadequate",
            },
            {
                "requirement": "Must not be used concurrently with another biologic or targeted synthetic DMARD",
                "patient_friendly": "You cannot take Rituximab at the same time as another biologic medication",
                "action_needed": "Your doctor needs to confirm you've stopped any other biologic drugs before starting Rituximab",
            },
            {
                "requirement": "Preferred product step therapy: must try Truxima, Riabni, and Ruxience before brand Rituxan",
                "patient_friendly": "You must try all three biosimilar versions before your plan will cover brand-name Rituxan",
                "action_needed": "Your doctor must document that you tried each biosimilar and experienced a significant allergy or serious adverse reaction due to an inactive ingredient difference",
            },
        ],
        "step_therapy_roadmap": [
            {
                "step_number": 1,
                "drug_name": "Truxima (rituximab-abbs)",
                "patient_explanation": "Cigna requires you to start with Truxima, a biosimilar version of Rituxan. It has the same active ingredient and works the same way.",
                "duration": "Varies by indication (1 month to 1 year approvals)",
                "tip": "Truxima is the first-line preferred product. Most patients respond identically to Rituxan.",
            },
            {
                "step_number": 2,
                "drug_name": "Riabni (rituximab-arrx)",
                "patient_explanation": "If Truxima caused a reaction due to an inactive ingredient, Riabni is the next biosimilar option.",
                "duration": "Varies by indication",
                "tip": "The reaction must be specifically due to a formulation difference (e.g., stabilizer, buffer, or surfactant) — not the active ingredient.",
            },
            {
                "step_number": 3,
                "drug_name": "Ruxience (rituximab-pvvr)",
                "patient_explanation": "If both Truxima and Riabni caused reactions, Ruxience is the third biosimilar to try before brand Rituxan.",
                "duration": "Varies by indication",
                "tip": "Documentation of the specific inactive ingredient causing each reaction is required.",
            },
            {
                "step_number": 4,
                "drug_name": "Rituxan (rituximab)",
                "patient_explanation": "Brand-name Rituxan is only covered after documented allergic or adverse reactions to all three biosimilars due to inactive ingredient differences.",
                "duration": "Varies by indication",
                "tip": "Keep detailed records of each biosimilar reaction — the plan requires documentation proving inactive ingredient caused the issue.",
            },
        ],
        "patient_summary": "Cigna covers Rituximab for many conditions beyond cancer, including rheumatoid arthritis, MS, lupus, and more. Each condition has specific requirements — for example, RA requires trying a standard medication first for 3 months, and MS requires failing two other therapies. You must try three biosimilar versions (Truxima, Riabni, Ruxience) before brand-name Rituxan is covered.",
    },
    {
        "drug_name": "Bevacizumab (Avastin)",
        "payer_name": "Florida Blue",
        "hcpcs_code": "J9035",
        "covered_indications": [
            "Metastatic colorectal cancer",
            "Non-squamous non-small cell lung cancer",
            "Recurrent glioblastoma",
            "Metastatic renal cell carcinoma",
            "Cervical cancer (persistent, recurrent, or metastatic)",
            "Ovarian/fallopian tube/primary peritoneal cancer",
            "Hepatocellular carcinoma (with atezolizumab)",
            "Mesothelioma (pleural and peritoneal)",
            "Ampullary cancer",
            "Small bowel adenocarcinoma",
            "Soft tissue sarcoma (angiosarcoma)",
            "Uterine neoplasm",
            "Vaginal cancer",
            "Vulvar cancer",
            "CNS cancer / radiation necrosis",
            "Hereditary hemorrhagic telangiectasia",
        ],
        "prior_auth_checklist": [
            {
                "requirement": "FDA-approved indication or NCCN Category 1/2A recommendation",
                "patient_friendly": "Your cancer type must be on the approved list, or your doctor can cite national cancer treatment guidelines supporting its use",
                "action_needed": "Your oncologist should reference the specific NCCN guideline category when submitting the prior auth",
            },
            {
                "requirement": "Dose must not exceed 10 mg/kg every 2 weeks or 15 mg/kg every 3 weeks",
                "patient_friendly": "The prescribed dose must be within standard limits based on your weight and treatment schedule",
                "action_needed": "Your doctor will calculate the appropriate dose based on your body weight",
            },
            {
                "requirement": "For Avastin specifically: documented inadequate response, contraindication, or intolerance to Mvasi OR Zirabev",
                "patient_friendly": "Before getting brand-name Avastin, you must try one of the two preferred lower-cost versions (Mvasi or Zirabev) and it must not work or cause problems",
                "action_needed": "Your doctor must submit documentation of the issue with Mvasi or Zirabev — a paid claim within the past 90 days from a prior health plan can exempt you from this requirement",
            },
            {
                "requirement": "Indication-specific criteria must be met (e.g., specific combination regimens, disease stage)",
                "patient_friendly": "The drug must be used in the specific combinations and disease situations listed for your cancer type",
                "action_needed": "Your oncologist needs to specify which treatment regimen they're using and confirm it matches the policy requirements",
            },
        ],
        "step_therapy_roadmap": [
            {
                "step_number": 1,
                "drug_name": "Mvasi (bevacizumab-awwb) or Zirabev (bevacizumab-bvzr)",
                "patient_explanation": "Florida Blue requires you to try one of the preferred biosimilar versions first. Either Mvasi or Zirabev will work — they're clinically identical to brand Avastin.",
                "duration": "180-day initial approval",
                "tip": "Florida Blue only requires trying ONE of these two (not both), which is less restrictive than some other plans.",
            },
            {
                "step_number": 2,
                "drug_name": "Avastin (bevacizumab) or other biosimilars",
                "patient_explanation": "If the preferred biosimilar didn't work for you (inadequate response, intolerance, or contraindication), your plan will cover Avastin or other biosimilar options.",
                "duration": "1-year continuation approval",
                "tip": "If you were on Avastin with a prior health plan within the past 90 days, you may be exempt from step therapy — ask your doctor to submit the paid claim documentation.",
            },
        ],
        "patient_summary": "Florida Blue covers bevacizumab for a wide range of cancers. You must first try a preferred biosimilar (Mvasi or Zirabev) before brand-name Avastin is covered. Initial approvals last 180 days, with 1-year renewals after that. If you were recently on Avastin with a different insurance plan, you may be exempt from the biosimilar requirement.",
    },
    {
        "drug_name": "Botox (onabotulinumtoxinA)",
        "payer_name": "UnitedHealthcare",
        "hcpcs_code": "J0585",
        "covered_indications": [
            "Cervical dystonia (spasmodic torticollis)",
            "Blepharospasm associated with dystonia",
            "Chronic migraine headache (prophylaxis)",
            "Spasticity (upper and lower limb)",
            "Overactive bladder",
            "Strabismus",
            "Hyperhidrosis (including Frey's syndrome)",
            "Sialorrhea",
            "Hemifacial spasm",
            "Chronic anal fissures",
            "Achalasia",
            "Essential tremor",
            "Hand dystonia",
            "Oromandibular dystonia",
            "Spasmodic dysphonia (laryngeal dystonia)",
        ],
        "prior_auth_checklist": [
            {
                "requirement": "Documented diagnosis",
                "patient_friendly": "Your doctor must confirm your specific diagnosis in the prior auth request",
                "action_needed": "Make sure your medical records clearly document your diagnosis with the appropriate ICD-10 code",
            },
            {
                "requirement": "Administration no more frequent than every 12 weeks",
                "patient_friendly": "Botox injections must be at least 12 weeks (about 3 months) apart, regardless of what condition is being treated",
                "action_needed": "Schedule your Botox appointments at least 12 weeks apart — more frequent treatments will be denied",
            },
            {
                "requirement": "Dosing per FDA labeling or published clinical evidence",
                "patient_friendly": "The amount of Botox used must follow standard medical guidelines for your condition",
                "action_needed": "Your doctor must attest that the dosing follows FDA-approved labeling or published evidence",
            },
            {
                "requirement": "For chronic migraine: >= 15 headache days/month, >= 8 migraine days/month, headaches lasting 4+ hours",
                "patient_friendly": "For migraine treatment, you must have at least 15 headache days per month, with at least 8 of them being migraines, and headaches that last 4 or more hours",
                "action_needed": "Keep a headache diary for at least one month documenting frequency, type (migraine vs. tension), and duration of each headache",
            },
        ],
        "step_therapy_roadmap": [],
        "patient_summary": "UnitedHealthcare covers Botox for many conditions including chronic migraine, cervical dystonia, spasticity, and overactive bladder. There's no step therapy for Botox specifically (it IS the preferred product), but injections must be at least 12 weeks apart. For chronic migraine, you must meet specific frequency criteria: at least 15 headache days per month with 8+ migraine days.",
    },
    {
        "drug_name": "Myobloc (rimabotulinumtoxinB)",
        "payer_name": "UnitedHealthcare",
        "hcpcs_code": "J0587",
        "covered_indications": [
            "Cervical dystonia (spasmodic torticollis)",
            "Detrusor overactivity",
            "Sialorrhea",
            "Spasticity",
        ],
        "prior_auth_checklist": [
            {
                "requirement": "Documented diagnosis",
                "patient_friendly": "Your doctor must confirm your specific diagnosis in the prior auth request",
                "action_needed": "Make sure your medical records clearly document your diagnosis",
            },
            {
                "requirement": "Administration no more frequent than every 12 weeks",
                "patient_friendly": "Injections must be at least 12 weeks (about 3 months) apart",
                "action_needed": "Schedule appointments at least 12 weeks apart",
            },
            {
                "requirement": "History of failure, contraindication, or intolerance to Botox, Dysport, or Xeomin",
                "patient_friendly": "You must first try one of the other botulinum toxin brands (Botox, Dysport, or Xeomin) and it must not work, cause problems, or be unsafe for you",
                "action_needed": "Your doctor must document which product you tried, for how long, and why it wasn't suitable",
            },
            {
                "requirement": "Initial authorization for no more than 12 months",
                "patient_friendly": "Your first approval will last up to 12 months, after which your doctor will need to request renewal",
                "action_needed": "Plan to have your doctor submit a renewal request before your 12-month authorization expires",
            },
        ],
        "step_therapy_roadmap": [
            {
                "step_number": 1,
                "drug_name": "Botox, Dysport, or Xeomin",
                "patient_explanation": "UnitedHealthcare requires you to first try one of the Type A botulinum toxins (Botox, Dysport, or Xeomin). These are the preferred treatments for your condition.",
                "duration": "At least one trial with documented outcome",
                "tip": "Your doctor can choose which Type A product to try first based on your specific condition and their clinical experience.",
            },
            {
                "step_number": 2,
                "drug_name": "Myobloc (rimabotulinumtoxinB)",
                "patient_explanation": "If the Type A toxin didn't work, caused intolerable side effects, or is medically unsafe for you, Myobloc (a Type B toxin) will be covered.",
                "duration": "12-month initial approval",
                "tip": "Make sure your doctor clearly documents why the Type A product wasn't suitable — 'failure' means it didn't adequately treat your symptoms.",
            },
        ],
        "patient_summary": "UnitedHealthcare covers Myobloc for cervical dystonia, overactive bladder, sialorrhea, and spasticity, but only after you've tried a Type A botulinum toxin first (Botox, Dysport, or Xeomin). If the Type A product failed, caused intolerable effects, or was contraindicated, Myobloc is covered with 12-month authorizations.",
    },
]
